version: "2"
services:

  datastore:
    build:
      context: .
      dockerfile: build/Dockerfile.data
    volumes:
      - .:/opt/data

  nginx:
    build:
      context: .
      dockerfile: build/Dockerfile.nginx
    ports:
      - "80:80"
    volumes_from:
      - datastore
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: build/Dockerfile.php-fpm
    ports:
      - "9000:9000"
    volumes_from:
      - datastore
    links:
      - db
      - redis

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    volumes_from:
      - datastore

  redis:
    image: redis:3-alpine