version: "2"
services:

  datastore:
    image: xtreamwayz/datastore:latest
    container_name: UNIQUE_NAME-datastore
    volumes:
      - .:/app

  web:
    image: xtreamwayz/nginx:latest
    container_name: UNIQUE_NAME-web
    ports:
      - "80:80"
    volumes_from:
      - datastore
    links:
      - php

  php:
    image: xtreamwayz/php:latest
    container_name: UNIQUE_NAME-php
    ports:
      - "9000:9000"
    volumes_from:
      - datastore
    links:
      - db
      - redis
      - mailhog

  db:
    image: mysql:5.7
    container_name: UNIQUE_NAME-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    volumes_from:
      - datastore

  redis:
    image: redis:3-alpine
    container_name: UNIQUE_NAME-redis
    ports:
      - "6379:6379"

  mailhog:
    image: xtreamwayz/mailhog:latest
    container_name: UNIQUE_NAME-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
