version: "2"
services:

  datastore:
    image: busybox
    container_name: UNIQUE_NAME-datastore
    volumes:
      - .:/app

  web:
    image: xtreamwayz/nginx
    container_name: UNIQUE_NAME-web
    ports:
      - "80:80"
    volumes_from:
      - datastore
    links:
      - php

  php:
    image: xtreamwayz/php
    container_name: UNIQUE_NAME-php
    ports:
      - "9000:9000"
    volumes_from:
      - datastore
    links:
      - db
      - redis
      - mailhog

  db:
    image: xtreamwayz/mysql
    container_name: UNIQUE_NAME-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    volumes_from:
      - datastore

  redis:
    image: redis:3-alpine
    container_name: UNIQUE_NAME-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: UNIQUE_NAME-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  node:
    image: node:slim
    container_name: UNIQUE_NAME-node
    volumes_from:
      - datastore
    working_dir: /app
    command: npm install --no-bin-links
